---
title: "SPARQL Query Examples"
output:
  html_document:
    toc: true
    number_sections: true
---
<style type="text/css">
.main-container {
    max-width: 1800px;
    margin-left: auto;
    margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(lubridate)
library(igraph)
library(tidyverse)
library(tidytext)

here::i_am("README.md")

network_folder <- here("data/clean/networks")

theme_set(theme_classic())
```


```{r}
network_paths <- list.files(network_folder, pattern = "\\.gml$", full.names = T)

df <- tibble()

for (file in network_paths) {
  name <- basename(file) %>% str_replace(".gml$", "")
  graph <- igraph::read_graph(file, format = "gml")
  nodes <- igraph::as_data_frame(graph, "vertices")
  nodes$network <- name
  df <- bind_rows(df, nodes)
}
```


```{r}
conspiracy_topics <- c(
  "plandemic", "5g_covid", "is_earth_flat", "pizzagate",
  "adrenochrome", "qanon", "chemtrails", "great_replacement_theory",
  "9_11_building_7", "death_elvis_presley"
)
noncontroversial_topics <- c(
  "how_to_draw", "ab_workout", "warrior_cats",
  "vintage_jewelry", "pokemon_go", "minecraft", "wordle", "van_life_us",
  "power_tools", "urban_gardening"
)
news_topics <- c(
  "dominion_voting_system", "roe_v_wade", "critical_race_theory",
  "johnny_depp_amber_heard_trial", "vaccine_mandate", "derek_chauvin",
  "baby_formula", "transgender", "antifa", "gas_prices"
)
science_topics <- c(
  "game_theory", "filter_bubbles", "nft", "climate_change",
  "monkeypox_virus", "nanotechnology", "blockchain", "machine_learning", "autism",
  "tourette_syndrome"
)
```


# Sentiment analysis

## by network


```{r}
df <- df %>%
  mutate(
    topic_group = case_when(
      network %in% conspiracy_topics ~ "conspiracy",
      network %in% noncontroversial_topics ~ "non-controversial",
      network %in% news_topics ~ "news",
      network %in% science_topics ~ "science"
    )
  )
```

```{r}

df %>%
  group_by(topic_group, network) %>%
  summarize(
    avg_sentiment = mean(sentiment)
  ) %>%
  ggplot(aes(x = reorder(network, avg_sentiment), y = avg_sentiment, fill = topic_group)) +
  geom_col() +
  coord_flip()
```

## by topic group

```{r}
df %>%
  group_by(topic_group) %>%
  summarize(
    avg_sentiment = mean(sentiment)
  ) %>%
  ggplot(aes(x = reorder(topic_group, avg_sentiment), y = avg_sentiment)) +
  geom_col() +
  xlab("Group") +
  coord_flip()

# ggsave(here("sentiment_basic.pdf"), width = 6, height = 3)
```

# Perspective API Analysis


## by network


```{r, fig.width=15, fig.height=7}

perspective_plot <- df %>%
  select(-c(PERSPECTIVE_FLIRTATION, PERSPECTIVE_THREAT, PERSPECTIVE_SEXUALLY_EXPLICIT, PERSPECTIVE_PROFANITY)) %>%
  pivot_longer(starts_with("PERSPECTIVE_"), names_to = "perspective_type") %>%
  group_by(topic_group, network, perspective_type) %>%
  summarize(avg_val = mean(value)) %>%
  ungroup() %>%
  ggplot(aes(x = topic_group, y = avg_val, label = network)) +
  stat_summary(fun = mean, geom = "bar", fill = "#BED1DB", color = "black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = .2) +
  ylab("Avg. probability") +
  geom_text(color = "#658DA0", size = 3, alpha = 1) +
  facet_wrap(~perspective_type, ncol = 2, scales = "free")

perspective_plot

#ggsave(here("perspective_plot.pdf"), width = 16, height=9)
```


# Correlation between LR and indegree

```{r}
df %>%
  mutate(leftright = ifelse(leftright %in% c("Inf", ""), "Unk", leftright)) %>%
  group_by(topic_group, network, leftright) %>%
  summarize(avg_indegree = mean(indegree)) %>%
  ungroup() %>%
  ggplot(aes(x = fct_relevel(leftright, "L", "C", "R"), y = avg_indegree, label = network)) +
  stat_summary(fun = mean, geom = "bar", fill = "#BED1DB", color = "black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = .2) +
  ylab("Avg. indegree") +
  xlab("Channel's political orientation") +
  geom_text(color = "#658DA0", size = 3, alpha = 1) +
  facet_wrap(~topic_group)

ggsave(here("lr_indegree.pdf"), width=10, height=6)
```
